easy_admin:
    entities:
       # List the entity class name you want to manage
        - App\Entity\Utilisateur
            controller: App\Controller\UtilisateurController
            list:
              fields:
                - contract
                - { property: 'contract', template: 'contract.html.twig' }
                # - { property: 'roles', }
        - App\Entity\Trajet
        - App\Entity\Client
        - App\Entity\Frais
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.scans%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.scans%' }
            form:
                fields:
                  - { property: 'imageFile', type: 'vich_image' }
            
