#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
    path: /test
    controller: App\Controller\PetitTestController::index

frais:
    path: /frais
    controller: App\Controller\FraisController::index

client:
    path: /client
    controller: App\Controller\ClientController::index